### ISSUE TITLE
User can view all deals

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/ajax-project#1]
Plan:
Create a responsive page where users can view PC digital game deals

Wireframe:

![image](https://user-images.githubusercontent.com/69335064/98718048-c2538800-2342-11eb-9e5e-939fadf26c6f.png)

## ✅ Task List

- [x] Set up basic header
- [x] Pick fonts for header and body text
- [x] Finalize color scheme
- [x] Create header 
- [x] Create data-view for current page
- [x] Create sample div elements for deal listings
- [x] Apply CSS styling
- [x] Add event listener to toggle favorite button
- [x] Check mobile and desktop view. Apply any changes necessary
- [x] Create Data Model
- [x] Use API and create DOM tree based off sample deal listings
