### ISSUE TITLE
User will be able to look up more info on the game

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/ajax-project#3]
Plan:
Users can click on the "More Info" button to see additional information about the game

Wireframe:

![image](https://user-images.githubusercontent.com/69335064/98858034-cc45bb80-2414-11eb-8228-ff92fba9063c.png)

## ✅ Task List

- [x] Hide the div[data-view="deals-page"] view in HTML
- [x] Create new data-view element for the More-Info page
- [x] Set up example HTML
- [x] Apply CSS
- [x] Ensure profile view looks good on mobile and desktop
- [x] Update data model with appropriate information
- [x] Create DOM tree that matches example HTML
- [x] Define JS view swapping function that takes the name of which 'data-view' to show and hides all others
- [x] Make view swapping function also write the name of the view it showed to the application's data model
- [x] Test view swapping function 
- [x] Define JS function that takes the profile data model and returns DOM tree that matches HTML
- [x] Make sure desktop and mobile view looks good
- [x] Add event listener to the back button to go to the deals page
- [x] Create new data-view element for the home-page
- [x] Set up HTML and CSS for home-page
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality
- [x] Fix bugs
