### ISSUE TITLE
User will be able to favorite games

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/ajax-project#4]
Plan:
Users can click on a button to favorite the game they are interested in

Wireframe:

![image](https://user-images.githubusercontent.com/69335064/99468700-0243dd80-28f6-11eb-8955-561c6ab3d0dd.png)

![image](https://user-images.githubusercontent.com/69335064/99468704-05d76480-28f6-11eb-8b03-57fa54d7a604.png)

## ✅ Task List

- [x] User can toggle favorite button 
- [x] Toggled state will save when leaving the page
- [x] Create div view element for favorites page
- [x] Push favorited items to data model
- [x] Remove favorited item from data model if user unfavorites item
- [x] Remove unnecessary CSS
