### ISSUE TITLE
User can view favorited games

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/ajax-project#5]
Plan:
Users will be able to look at a list of their favorited items

Wireframe:

![image](https://user-images.githubusercontent.com/69335064/98619478-2bda8480-22b8-11eb-844d-53584299ff8a.png)

## ✅ Task List

- [x] Create data-view for favorites page
- [x] Set favorited icons to local storage
- [x] Set favorited game info to local storage
- [x] User can remove favorited games from favorites list
- [x] Corresponding game will be unfavorited from deals page
- [x] Remove any unnecessary CSS
- [x] Check functionality
